### ISSUE TITLE
MakeFile error on OSX

### ISSUE THREAD

**Issue by gizak** [slate/slate#84]
I stucked with an error when running `make`, here's log:

```
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository '/Users/Gizak/.npm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.131]: errno=Operation timed out
npm ERR! Error: Command failed: Cloning into bare repository '/Users/Gizak/.npm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Socket.<anonymous> (child_process.js:956:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Gizak/Desktop/slate
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Gizak/Desktop/slate/npm-debug.log
npm ERR! not ok code 0
make: *** [node_modules] Error 1
```

I guess this was because `git clone git://github.com/ariya/esprima.git` failed when npm was installing dependency `component ~0.19.7`. I tried install `esprima.git` manually, surprisingly it failed as before :-!  It seems that there is something wrong with the repo.

So, Any workaround to solve this?

**Comment by tj** [comment]
should be fine now, i think npm was having issues for a bit
